version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: dnaxfbdl
      POSTGRES_USER: dnaxfbdl
      POSTGRES_PASSWORD: u_WGP5nym4_5tCQW7s8HRjVF4Q9ojxdy
    ports:
      - "5432:5432"

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dnaxfbdl
      - SPRING_DATASOURCE_USERNAME=dnaxfbdl
      - SPRING_DATASOURCE_PASSWORD=u_WGP5nym4_5tCQW7s8HRjVF4Q9ojxdy
